version: "3.8"

volumes:
     devrydata:
          name: devry-services-data

services:
     devry-services:
          container_name: DeVryBot
          hostname: devrybot_host
          environment:
               TZ: "America/New_York"
          image: "mercenary9312/unofficial-devry-service-bot:latest"
          restart: "always"
          volumes:
               - devrydata:/app/Data:rw 