version: "3.8"

volumes:
     devrydata:
          name: devry_devry-services

services:
     devry-services:
          environment:
               TZ: "America/New_York"
          image: "mercenary9312/unofficial-devry-service-bot"
          restart: "always"
          volumes:
               - devrydata:/app/Data:rw